// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Todo = {
    id: string;
    title: string;
    description?: string | null;
    completed: boolean;
    created_at: string;
    updated_at: string;
};

export type TodoCreate = {
    title: string;
    description?: string | null;
    completed?: boolean;
};

export type TodoUpdate = {
    title?: string | null;
    description?: string | null;
    completed?: boolean | null;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type RootGetResponse = unknown;

export type GetTodosTodosGetData = {
    limit?: number;
    skip?: number;
};

export type GetTodosTodosGetResponse = Array<Todo>;

export type CreateTodoTodosPostData = {
    requestBody: TodoCreate;
};

export type CreateTodoTodosPostResponse = Todo;

export type GetTodoTodosTodoIdGetData = {
    todoId: string;
};

export type GetTodoTodosTodoIdGetResponse = Todo;

export type UpdateTodoTodosTodoIdPutData = {
    requestBody: TodoUpdate;
    todoId: string;
};

export type UpdateTodoTodosTodoIdPutResponse = Todo;

export type DeleteTodoTodosTodoIdDeleteData = {
    todoId: string;
};

export type DeleteTodoTodosTodoIdDeleteResponse = unknown;

export type SearchTodosTodosSearchGetData = {
    q: string;
};

export type SearchTodosTodosSearchGetResponse = Array<Todo>;

export type $OpenApiTs = {
    '/': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
    '/todos': {
        get: {
            req: GetTodosTodosGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: Array<Todo>;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        post: {
            req: CreateTodoTodosPostData;
            res: {
                /**
                 * Successful Response
                 */
                200: Todo;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/todos/{todo_id}': {
        get: {
            req: GetTodoTodosTodoIdGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: Todo;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        put: {
            req: UpdateTodoTodosTodoIdPutData;
            res: {
                /**
                 * Successful Response
                 */
                200: Todo;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: DeleteTodoTodosTodoIdDeleteData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/todos/search': {
        get: {
            req: SearchTodosTodosSearchGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: Array<Todo>;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
};